version: '3'

services:
  gh_runner:
    build:
      context: runner
      args:
        RUNNER_VERSION: 2.296.1
    environment:
      - GH_TOKEN=${GITHUB_TOKEN}
      - REG_TOKEN=${GITHUB_ACTION_RUNNER_TOKEN}
      - GH_OWNER=${GITHUB_OWNER}
      - GH_REPOSITORY=${GITHUB_REPOSITORY}
    hostname: actionrunner
    networks:
      gh_runner_net:
        ipv4_address: 172.18.0.2
  
  exploit:
    build:
      context: exploit-client
      dockerfile: Dockerfile
    hostname: remoteclient
    networks:
      gh_runner_net:
        ipv4_address: 172.18.0.3
  
networks:
  gh_runner_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
